Add feature to delete mutation, cancer type and treatments in curation page
oncokb/oncokb-transcript pull request #143
Opened 2023-12-07 20:08 UTC by calvinlu3

This fixes https://github.com/oncokb/oncokb/issues/3608

Todo(s):
- [x] Add tests for `isSectionRemovableWithoutReview`

### Delete icon in `Collapsible` 
![view](https://github.com/oncokb/oncokb-transcript/assets/59149377/306f3583-4ff3-469f-832e-46e400bf064f)

### Modal when item can be deleted immediately
![delete](https://github.com/oncokb/oncokb-transcript/assets/59149377/c5d89bce-ebb9-47dd-8b50-0a4a36ee7c76)

### Modal when item to be deleted needs review first
![delete_review](https://github.com/oncokb/oncokb-transcript/assets/59149377/4d1a8392-5956-42bc-8a40-00bd8647ea21)

2023-12-07 20:15 UTC, calvinlu3 commented
@zhx828 Could you take a look and provide some feedbacks? Thanks!

2023-12-08 15:09 UTC, zhx828 requested changes
<img width="275" alt="Screenshot 2023-12-08 at 10 05 51 AM" src="https://github.com/oncokb/oncokb-transcript/assets/5400599/547269be-91ac-4c05-b75d-5ea1d9e91467">
Let's add a divider between the action icons VS info icons. Could try to add m-2 on the divider. can also try m-3

2023-12-08 21:58 UTC, calvinlu3 commented on src/main/webapp/app/stores/firebase/firebase.gene.store.ts
> +      };
Changed to generate default using the Review constructor

2023-12-08 21:59 UTC, calvinlu3 commented on src/main/webapp/app/pages/curation/collapsible/styles.module.scss
> +  padding-right: 0 !important;
The padding don't seem to be taking priority over the `card-body` styles anymore.
Removing the `!important`:
![image](https://github.com/oncokb/oncokb-transcript/assets/59149377/9e5eae1f-5f9e-483b-bb79-e1a3ec4710b0)

2023-12-08 22:00 UTC, calvinlu3 commented on src/main/webapp/app/stores/firebase/firebase.gene.store.ts
> +      return Promise.reject(new Error('Cannot update collaborator with undefined name'));
Yeah thinking about it, this is not possible.

2023-12-08 22:00 UTC, calvinlu3 commented on src/main/webapp/app/stores/firebase/firebase.gene.store.ts
> +  isSectionRemoveableWithoutReview = (nestLevel: RemoveableNestLevel, sectionToRemovePath: string) => {
Added some tests

2023-12-08 22:06 UTC, calvinlu3 commented
Let me know if they look fine, or I should make some changes

For divider, some options below:
1px $grey (#808080)
![image](https://github.com/oncokb/oncokb-transcript/assets/59149377/8042b088-ef5b-4a07-970d-939267cfcaa2)

2px $grey (#808080)
![image](https://github.com/oncokb/oncokb-transcript/assets/59149377/8415a537-4410-455d-9d70-83e5b366aca2)



2px $medium-grey (#c5c5c5)
![image](https://github.com/oncokb/oncokb-transcript/assets/59149377/d2614b02-1012-4eb3-ad8b-2f49fe6f924a)

2023-12-08 22:36 UTC, zhx828 commented
> Let me know if they look fine, or I should make some changes
> 
> For divider, some options below: 1px $grey (#808080) ![image](https://private-user-images.githubusercontent.com/59149377/289199382-8042b088-ef5b-4a07-970d-939267cfcaa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNzUwNzEsIm5iZiI6MTcwMjA3NDc3MSwicGF0aCI6Ii81OTE0OTM3Ny8yODkxOTkzODItODA0MmIwODgtZWY1Yi00YTA3LTk3MGQtOTM5MjY3Y2ZjYWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDIyMzI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NDY3MzY4NGQ0MjVkOTZiN2I3OTMwMjlkMmY4Y2FhOTU0ODFjMTgyMzk3N2VkMjAyMmZkNzU5OTU5MDExOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T_3I_6cwDNtKSFdr86SYGHuZOxvZW7gdpmKQSXwYCuk)
> 
> 2px $grey (#808080) ![image](https://private-user-images.githubusercontent.com/59149377/289199583-8415a537-4410-455d-9d70-83e5b366aca2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNzUwNzEsIm5iZiI6MTcwMjA3NDc3MSwicGF0aCI6Ii81OTE0OTM3Ny8yODkxOTk1ODMtODQxNWE1MzctNDQxMC00NTVkLTlkNzAtODNlNWIzNjZhY2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDIyMzI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjYWJjMDUzNTA2N2E3NWI2NjgzYTM2NmIwMTA3MWUyY2M1NWVmODYwYjMzMzY3ZmNjM2EyMzkwODQxZDhhNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IvTYDQNWeIqoLHtiwJlvn-TTOla6GXW29dSfcuMRhWc)
> 
> 2px $medium-grey (#c5c5c5) ![image](https://private-user-images.githubusercontent.com/59149377/289199251-d2614b02-1012-4eb3-ad8b-2f49fe6f924a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNzUwNzEsIm5iZiI6MTcwMjA3NDc3MSwicGF0aCI6Ii81OTE0OTM3Ny8yODkxOTkyNTEtZDI2MTRiMDItMTAxMi00ZWIzLWFkOGItMmY0OWZlNmY5MjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDIyMzI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3YzU1ZTZkNzE1MjllMDlkOTc5Y2MzNWRmNGUxNGNjZGZlZDIwNDhkNzFjNzUyNWI1NjM4MzQ3MzdmOWVmOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WVJiPiAabI8GqnfLwIDHZaxa64YFEMatA79_rDCbRLI)

- Can we use the same color of the Collapsible border? I would also use the same border width. 
- Change the trash icon to black please

2023-12-12 21:50 UTC, zhx828 approved these changes
Looks good. One minor comment.

2023-12-12 21:50 UTC, zhx828 commented on src/main/webapp/app/pages/curation/CurationPage.tsx
> +                    firebasePath={getFirebasePath('MUTATIONS', hugoSymbol, mutationIndex)}
I suppose the IDE will give warning when the path is not in FB_COLLECTION_PATH?

2023-12-12 21:50 UTC, zhx828 commented on src/main/webapp/app/stores/firebase/firebase.gene.store.spec.ts
> +describe('FirebaseGeneStore', () => {
👍🏼

2023-12-13 21:01 UTC, merged