Add validation tool
oncokb/oncokb-transcript pull request #262
Opened 2024-03-29 19:54 UTC by jfkonecn

resolves oncokb/oncokb#3703

2024-03-29 21:13 UTC, jfkonecn commented on src/main/java/org/mskcc/oncokb/curation/web/rest/ClientForwardController.java
>      public String forward() {
Need to fix this. It's blocking websocket from working.

2024-04-01 20:42 UTC, zhx828 commented
Some feature requests before code review
- for success test/info, we should not allow the collapsible to open. See deleted `test` mutation in https://curation.oncokb.org/curation/ZNRF3/somatic as an example
- we need to notify the user the validation is done. Maybe add a toast banner?
- Let's change the Variant column header to `Biomarker`
- the Validate button does not need to be wrapped in a container again. Otherwise you will see extra white space on the left of the button comparing to Tools tab
- I don't think the refresh icon should be shown up before the first time of validation. And the button should be primary button before first time of validation. See `Release Gene` button in the gene page under the Tools tab

2024-04-03 20:56 UTC, bprize15 commented on src/main/webapp/app/components/tabs/CurationDataValidationTab.tsx
> +        <Col>
Could you remove the padding on the column so it lines up nicely with the tab titles?

2024-04-03 20:57 UTC, bprize15 commented on src/main/webapp/app/components/tabs/CurationDataValidationTab.tsx
> +    toast.success('Validation completed!');
We have utility functions `notifySuccess` and `notifyError` for this

2024-04-03 20:57 UTC, bprize15 commented on src/main/webapp/app/components/tabs/CurationDataValidationTab.tsx
> +    toast.error('Error while attempting to validate. Please try again.');
Can use `notifyError` here

2024-04-03 21:00 UTC, bprize15 commented on src/main/webapp/app/pages/curation/collapsible/Collapsible.tsx
> +    if (isPendingDeleteRef.current === isPendingDelete && displayOptionsJson === oldDisplayOptionsJson) {
Can delete this I'd imagine

2024-04-05 03:43 UTC, zhx828 requested changes
For some reason, the validation websocket doesn't work after recent changes. I will test again.

2024-04-05 03:43 UTC, zhx828 commented on .nvmrc
> +14.17.6
I noticed this is added in few of your prs. When .nvmrc file is specified, nvm will switch to the version automatically?

2024-04-05 03:43 UTC, zhx828 commented on src/main/docker/keycloak.yml
> +      - kc-network
Curious why we create a new network

2024-04-05 03:43 UTC, zhx828 commented on src/main/java/org/mskcc/oncokb/curation/web/websocket/ProxyCurationValidationApiHandler.java
> +        this.validationEndpoint = url + "/api/websocket/curation/validation";
Should we move this to the application as well?

2024-04-05 03:43 UTC, zhx828 commented on src/main/webapp/app/components/tabs/CurationDataValidationTab.tsx
> +  const url = relativeWebsocketUrlToAbsolute('/api/websocket/curation/validation');
I would prefer creating a websocket API in curation platform and let the server side routes certain URL pattern to the core service so we could also add other websockets as well.

2024-04-05 03:44 UTC, zhx828 commented
Also thanks for testing useMemo. I will take another look at it when possible. What's the conclusion on that?

2024-04-05 12:19 UTC, jfkonecn commented
> Also thanks for testing useMemo. I will take another look at it when possible. What's the conclusion on that?

It rerenders every time.
According to the [react docs](https://react.dev/reference/react/useMemo) it uses [Object.is()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is) to do the equality check which does a pointer check for the equality between two objects.

2024-04-05 19:01 UTC, zhx828 approved these changes
Could you create a ticket to follow through on swagger/util as we discussed? Thanks!

2024-04-05 19:04 UTC, merged