Show hotspot icon and exon info on mutation
oncokb/oncokb-transcript pull request #268
Opened 2024-04-05 19:23 UTC by zhx828

This fixes https://github.com/oncokb/oncokb-pipeline/issues/283 and https://github.com/oncokb/oncokb/issues/3694

2024-04-05 20:43 UTC, calvinlu3 requested changes

2024-04-05 20:43 UTC, calvinlu3 commented on src/main/java/org/mskcc/oncokb/curation/repository/AlterationRepository.java
> +        " alteration.consequence = :consequence and ((alteration.start <= :end and alteration.end >= :start) or (alteration.end >= :start and alteration.start <= :end)) "
```suggestion
        " alteration.consequence = :consequence and (alteration.start <= :end and alteration.end >= :start) "
```

This should be sufficient to check if two ranges overlap. The original had two duplicated conditioned with OR.

2024-04-05 20:44 UTC, zhx828 commented on src/main/java/org/mskcc/oncokb/curation/domain/enumeration/HotspotFlagEnum.java
> +    HOTSPOT_V1,
@calvinlu3 there is a V2 about to come out. I'm preping for that.

2024-04-05 20:50 UTC, calvinlu3 commented on src/main/webapp/app/pages/curation/mutation/MutationsSection.tsx
> +        annotatedAltsCache.fetch(hugoSymbol, snapshot.val());
`fetch` takes `hugoSymbol` and `MutationQuery[]`, but `snapshot.val()` here is actually of type `Mutation[]`.

2024-04-09 17:28 UTC, bprize15 commented on src/main/webapp/app/pages/curation/mutation/MutationsSection.tsx
> +  }, []);
Probably safer to add dependencies to dependency array

2024-04-09 17:30 UTC, bprize15 commented on src/main/webapp/app/shared/links/Linkout.tsx
> +  if (props.addHttpsProtocol === undefined || props.addHttpsProtocol) {
Are we defaulting to true here? In that case, think we should use default assignment

2024-04-09 18:15 UTC, merged