Update keylock YAML file
oncokb/oncokb-transcript pull request #293
Opened 2024-05-10 19:13 UTC by gebbing12

Closes oncokb/oncokb#3733

2024-05-10 21:05 UTC, calvinlu3 approved these changes
Works well for me. Thanks!

2024-05-13 13:59 UTC, jfkonecn requested changes

2024-05-13 13:59 UTC, jfkonecn commented on src/main/docker/keycloak.yml
>        KEYCLOAK_DATABASE_VENDOR: postgres
Some of these environment variables not correct for the new image.
Please double check them.

2024-05-14 14:53 UTC, jfkonecn approved these changes

2024-05-14 15:00 UTC, merged