Update associated variants
oncokb/oncokb-transcript pull request #323
Opened 2024-05-22 18:11 UTC by bprize15

resolves https://github.com/oncokb/oncokb-pipeline/issues/358

2024-05-22 18:30 UTC, zhx828 requested changes

2024-05-22 18:30 UTC, zhx828 commented on src/main/webapp/app/pages/curation/collapsible/MutationCollapsible.tsx
> +                  ? { overlay: <span>Cannot delete because mutation is associated with a genomic indicator</span> }
```suggestion
                  ? { overlay: <span>Cannot delete because mutation is associated with genomic indicator(s)</span> }
```

2024-05-22 18:30 UTC, zhx828 commented on src/main/webapp/app/shared/util/firebase/firebase-review-utils.tsx
> +      }
Could you add a comment here that we need to remove when working on https://github.com/oncokb/oncokb-pipeline/issues/389

2024-05-22 20:33 UTC, bprize15 commented on src/main/webapp/app/shared/modal/AddMutationModal.tsx
> +                <div>Cannot modify alterations associated with a genomic indicator</div>
Outdated comment, moved disabled wording to the edit button tooltip

2024-05-23 13:23 UTC, zhx828 requested changes

2024-05-23 13:23 UTC, zhx828 commented on src/main/webapp/app/pages/curation/collapsible/MutationCollapsible.tsx
> +  const isAssociatedWithGenomicIndicator = associatedGenomicIndicatorUuids.length > 0;
I don't think this will react when associatedGenomicIndicatorUuids is updated using the memo.

2024-05-23 13:23 UTC, zhx828 commented on src/main/webapp/app/pages/curation/review/ReviewPage.tsx
> +import { Mutation } from 'app/shared/model/firebase/firebase.model';
not used

2024-05-23 13:23 UTC, zhx828 commented on src/main/webapp/app/shared/table/GenomicIndicatorsTable.tsx
> +    fetchGenomicIndicators(genomicIndicatorsPath);
I'm a bit confused to make this call when the callback in this useEffect also does the same thing

2024-05-23 15:32 UTC, merged